### ISSUE TITLE
Training on Multi-GPU

### ISSUE THREAD

**Issue by reachpranjal** [robodhruv/visualnav-transformer#38]
Hi, I'm trying to train on custom carla data (image size: [256, 256]). I've modified the `gpu_ids` in config to train it on 4 GPUs but I ended up with this error.

```
Traceback (most recent call last):                                                                                    
  File "train.py", line 403, in <module>
    main(config)
  File "train.py", line 327, in main
    train_eval_loop_nomad(
  File "/home2/user/visualnav-transformer/train/vint_train/training/train_eval_loop.py", line 203, in train_eval_loop_nomad
    train_nomad(
  File "/home2/user/visualnav-transformer/train/vint_train/training/train_utils.py", line 701, in train_nomad
    visualize_diffusion_action_distribution(
  File "/home2/user/visualnav-transformer/train/vint_train/training/train_utils.py", line 1090, in visualize_diffusion_action_distribution
    model_output_dict = model_output(
  File "/home2/user/visualnav-transformer/train/vint_train/training/train_utils.py", line 974, in model_output
    obs_cond = model("vision_encoder", obs_img=batch_obs_images, goal_img=batch_goal_images, input_goal_mask=goal_mask)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.

File "/home2/user/visualnav-transformer/train/vint_train/models/nomad/nomad.py", line 24, in forward
    output = self.vision_encoder(kwargs["obs_img"], kwargs["goal_img"], input_goal_mask=kwargs["input_goal_mask"])
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/user/visualnav-transformer/train/vint_train/models/nomad/nomad_vint.py", line 85, in forward
    obsgoal_encoding = self.goal_encoder.extract_features(obsgoal_img) # get encoding of this img
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/efficientnet_pytorch/model.py", line 296, in extract_features
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/efficientnet_pytorch/model.py", line 122, in forward
    x = self._project_conv(x)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/user/miniconda3/envs/nomad_train/lib/python3.8/site-packages/efficientnet_pytorch/utils.py", line 275, in forward
    x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by reachpranjal** [comment]
Fixed.

**Comment by GaHooooo** [comment]
i meet same question, can u tell me how to fix it ? thanks
